#Uncomment when running dwm

# #bg
# feh --no-fehbg --bg-scale '/home/marc/working/save/backgrounds/wp1.jpg' &
# #comparator
# compton --no-fading-openclose &
# #status bar:
# /home/marc/working/environment/dwm/addons/status_bar/status_bar &
# # dunst
# dunst &
# #dropbox
# dropbox start &
# #emacs daemon
# emacs --daemon
# exec dwm

#external monitor name (left bottom port on xps13)

exec xmonad
