* .authinfo belongs in ~/.authinfo
* mbsyncrc is the config file for isync
* GPG Stuff:
** To encrypt a new password, the command is:
*** gpg2 -e -r <key> file
** As of 2021 the key I am using to encrypt is D11FB5FAD5131DBC.
** To list keys, do:
*** gpg2 --list-secret-keys --keyid-format LONG
*** The key is the text  on one of the sec lines after the "/".
* protonmail-bridge
- runs as a daemon
- use protonmail-bridge-cli (or something like that). It's much cleaner and easier to use
- run `protonmail-bridge --cli` to configure and read account info
- start the daemon
* goimapnotify stuff:
- Install goimapnotify
- Each goimapnotify config (should be one config per email) runs with a separate goimapnotify daemon. They are user processes (ie systemctl --user)
- To use, create imapnotify systemd services (one per email) with `systemctl --user edit goimapnotify@<email>.service
- example config:
    #+BEGIN_SRC
    [Unit]
    Description=Execute scripts on IMAP mailbox changes (new/deleted/updated messages) using IDLE, golang version.

    [Service]
    Type=simple
    ExecStart=
    ExecStart=/usr/bin/goimapnotify -conf /home/marc/working/dotfiles/mu4e/goimapnotify_proton.conf
    Restart=always
    RestartSec=30

    [Install]
    WantedBy=default.target
    #+END_SRC
- enable.
- every time one of the accounts gets an email, mbsync runs for that account
