#!/bin/bash

# Get the status from ProtonVPN CLI
VPN_STATUS=$(protonvpn status | grep "Status:")

# Check if the status contains the word 'Connected'
if [[ $VPN_STATUS == *"Connected"* ]]; then
    echo ""
else
    echo ""
fi
